/**
 * Cloud Image Analysis Pipeline
 *
 * Handles image analysis using Google Gemini via ai-sdk.
 * Implements three-phase analysis: description → decision → generation
 *
 * SECURITY: All untrusted inputs (filename, AI-generated description) are sanitized.
 */

import type { LanguageModel } from 'ai';
import { generateText } from 'ai';
import { buildProposedPath } from '@/entrypoints/offscreen/text-analysis/filename-builder';
import { getAutoApplyBehavior } from '@/entrypoints/shared/constants/confidence-thresholds';
import { formatPageContextForPrompt } from '@/entrypoints/shared/context/page-context-formatter';
import { debugLogger } from '@/entrypoints/shared/debug/logger';
import type { UpgradeProposal } from '@/entrypoints/shared/history/types';
import type {
  ImageIngestionResult,
  ImageUpgradeAnalysisRequest,
  ImageUpgradeAnalysisResponse,
} from '@/entrypoints/shared/integrations/image-analysis/types';
import { arrayBufferToBase64 } from '@/entrypoints/shared/utils/encoding';
import { sanitizeForPrompt } from '@/entrypoints/shared/utils/prompt-sanitization';
import { DATE_FORMAT_RULE, parseJsonResponse } from './helpers';
import { buildCloudImageAnalysisSummary } from './summary-builder';

interface CloudDecisionResponse {
  shouldRename: boolean;
  reason: string;
  confidence: number;
  explanation: string;
}

interface CloudFilenameResponse {
  filename: string;
  reasoning: string;
}

/**
 * Analyze image using Google Gemini
 *
 * @param model - Configured Gemini model instance
 * @param request - Image analysis request with settings
 * @param ingestion - Prepared image data and metadata
 * @returns Analysis response with proposal or null
 */
export async function analyzeImageWithGemini(
  model: LanguageModel,
  request: ImageUpgradeAnalysisRequest,
  ingestion: ImageIngestionResult,
): Promise<ImageUpgradeAnalysisResponse | null> {
  try {
    debugLogger.log('[AI Analysis Start cloud-gemini image]', {
      requestId: request.requestId,
      filename: request.filename,
      imageSize: `${ingestion.originalWidth}x${ingestion.originalHeight}`,
      resizedSize: `${ingestion.resizedWidth}x${ingestion.resizedHeight}`,
    });

    const currentFilename = request.baseline.final || request.filename;
    const sanitizedFilename = sanitizeForPrompt(currentFilename);

    // Build page context for prompts (already sanitized by formatter)
    const pageContextInfo = formatPageContextForPrompt(request.pageContext, {
      prefix: '\n\nThis image was downloaded from:',
    });

    // Convert blob to base64 for ai-sdk using browser-compatible method
    const arrayBuffer = await ingestion.blob.arrayBuffer();
    const base64 = arrayBufferToBase64(arrayBuffer);
    const dataUrl = `data:${ingestion.mimeType};base64,${base64}`;

    // Step 1: Describe the image
    const descriptionPrompt = `Describe this image in 1-2 sentences. Be specific and concise.${pageContextInfo}`;

    debugLogger.log('[AI Prompt cloud-gemini image describe]', {
      requestId: request.requestId,
      promptLength: descriptionPrompt.length,
      prompt: descriptionPrompt,
    });
    console.log('[AI Prompt cloud-gemini image describe]\n', descriptionPrompt);

    const descriptionResult = await generateText({
      model,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: descriptionPrompt,
            },
            {
              type: 'image',
              image: dataUrl,
            },
          ],
        },
      ],
      temperature: 0.3,
    });

    debugLogger.log('[AI Response cloud-gemini image describe]', {
      requestId: request.requestId,
      responseLength: descriptionResult.text.length,
      response: descriptionResult.text,
    });

    const description = descriptionResult.text;
    // Note: Description is AI-generated by Gemini, not untrusted input
    // No need to sanitize - it's already from our own AI model

    // Step 2: Decision phase
    const decisionPrompt = `Should this image filename be improved?

Current filename: ${sanitizedFilename}
Image description: ${description}

Respond with JSON:
{
  "shouldRename": boolean,
  "reason": "string",
  "confidence": number (0.0-1.0),
  "explanation": "brief explanation"
}`;

    debugLogger.log('[AI Prompt cloud-gemini image decision]', {
      requestId: request.requestId,
      promptLength: decisionPrompt.length,
      prompt: decisionPrompt,
    });
    console.log('[AI Prompt cloud-gemini image decision]\n', decisionPrompt);

    const decisionResult = await generateText({
      model,
      prompt: decisionPrompt,
      temperature: 0.3,
    });

    debugLogger.log('[AI Response cloud-gemini image decision]', {
      requestId: request.requestId,
      responseLength: decisionResult.text.length,
      response: decisionResult.text,
    });

    const decision = parseJsonResponse<CloudDecisionResponse>(
      decisionResult.text,
    );

    debugLogger.log('[AI Parsed cloud-gemini image decision]', {
      requestId: request.requestId,
      parsed: decision,
    });

    if (!decision.shouldRename) {
      console.log('[CloudAI] Keeping baseline image filename', {
        requestId: request.requestId,
        reason: decision.reason,
      });
      return null;
    }

    // Step 3: Generate filename
    const generationPrompt = `Generate a descriptive filename for this image.

Description: ${description}
Current name: ${sanitizedFilename}
Max length: ${request.settings.maxFilenameLength} characters
Separator: ${request.settings.separator}

Rules:
- Subject first, then qualifiers
- Use ${request.settings.separator} as word separator
- ${DATE_FORMAT_RULE}
- No file extension
- Be specific
- Length: 20-${request.settings.maxFilenameLength} chars

Respond with JSON:
{
  "filename": "the generated filename stem",
  "reasoning": "brief explanation"
}`;

    debugLogger.log('[AI Prompt cloud-gemini image generation]', {
      requestId: request.requestId,
      promptLength: generationPrompt.length,
      prompt: generationPrompt,
    });
    console.log(
      '[AI Prompt cloud-gemini image generation]\n',
      generationPrompt,
    );

    const generationResult = await generateText({
      model,
      prompt: generationPrompt,
      temperature: 0.5,
    });

    debugLogger.log('[AI Response cloud-gemini image generation]', {
      requestId: request.requestId,
      responseLength: generationResult.text.length,
      response: generationResult.text,
    });

    const generated = parseJsonResponse<CloudFilenameResponse>(
      generationResult.text,
    );

    debugLogger.log('[AI Parsed cloud-gemini image generation]', {
      requestId: request.requestId,
      parsed: generated,
    });

    // Build proposal
    const proposedFilename = `${generated.filename}.${request.filename.split('.').pop()}`;
    const proposedPath = buildProposedPath(
      request.relativePath,
      proposedFilename,
    );

    const behavior = getAutoApplyBehavior(decision.confidence);

    const proposal: UpgradeProposal = {
      proposedFilename,
      proposedPath,
      confidenceScore: behavior.confidence,
      autoApply: behavior.shouldAutoApply,
      reasonTags: ['cloud', 'gemini', 'image'],
      generatedAt: Date.now(),
      source: 'ai',
      summary: buildCloudImageAnalysisSummary(
        description,
        decision.explanation,
      ),
    };

    debugLogger.log('[AI Analysis Complete cloud-gemini image]', {
      requestId: request.requestId,
      status: 'success',
      proposedFilename,
    });

    return {
      status: 'success',
      requestId: request.requestId,
      analyzedAt: Date.now(),
      proposal,
      description,
      modelSource: 'cloud',
      promptConfidence: behavior.confidence,
      promptUsed: true,
      decisionReason: decision.reason,
      metrics: {
        bytesFetched: ingestion.metrics.readBytes,
        requests: 3,
        elapsedMs: ingestion.metrics.elapsedMs,
        promptCalls: 3,
        decisionConfidence: behavior.confidence,
        resizeRatio: ingestion.resizeRatio,
        originalWidth: ingestion.originalWidth,
        originalHeight: ingestion.originalHeight,
        resizedWidth: ingestion.resizedWidth,
        resizedHeight: ingestion.resizedHeight,
      },
    };
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : JSON.stringify(error);

    debugLogger.error('[AI Error cloud-gemini image]', {
      requestId: request.requestId,
      error: errorMessage,
      filename: request.filename,
    });

    return {
      status: 'error',
      requestId: request.requestId,
      analyzedAt: Date.now(),
      error: 'Cloud AI image analysis failed',
      details: error instanceof Error ? error.message : String(error),
    };
  }
}
