/**
 * Shared file-related constants used across the application
 */

import type { FileType } from '@/entrypoints/shared/settings/settings';
import { FileTypeEnum } from '@/entrypoints/shared/settings/types';

// Multi-part archive extensions that need special handling
export const MULTI_PART_ARCHIVE_EXTENSIONS = [
  'tar.gz',
  'tar.bz2',
  'tar.xz',
  'tar.zst',
  'tar.lz',
  'tar.lz4',
  'tar.sz',
  'tar.br',
] as const;

// Type-safe multi-part extension type
export type MultiPartArchiveExtension =
  (typeof MULTI_PART_ARCHIVE_EXTENSIONS)[number];

// MIME type to file type mappings
export const MIME_TYPE_MAP: Record<string, FileType> = {
  'application/pdf': FileTypeEnum.PDF,
  'application/x-pdf': FileTypeEnum.PDF,
  'application/illustrator': FileTypeEnum.IMAGE,
  'application/postscript': FileTypeEnum.IMAGE,
  'application/zip': FileTypeEnum.ARCHIVE,
  'application/x-zip-compressed': FileTypeEnum.ARCHIVE,
  'application/x-7z-compressed': FileTypeEnum.ARCHIVE,
  'application/x-rar-compressed': FileTypeEnum.ARCHIVE,
  'application/vnd.rar': FileTypeEnum.ARCHIVE,
  'application/x-bzip2': FileTypeEnum.ARCHIVE,
  'application/x-gzip': FileTypeEnum.ARCHIVE,
  'application/gzip': FileTypeEnum.ARCHIVE,
  'application/x-xz': FileTypeEnum.ARCHIVE,
  'application/zstd': FileTypeEnum.ARCHIVE,
  'application/x-zstd-compressed': FileTypeEnum.ARCHIVE,
  'application/x-tar': FileTypeEnum.ARCHIVE,
  'application/x-iso9660-image': FileTypeEnum.ARCHIVE,
  'application/x-apple-diskimage': FileTypeEnum.ARCHIVE,
  'application/x-diskcopy': FileTypeEnum.ARCHIVE,
  'application/x-msdownload': FileTypeEnum.ARCHIVE,
  'application/vnd.microsoft.portable-executable': FileTypeEnum.ARCHIVE,
  'application/x-msi': FileTypeEnum.ARCHIVE,
  'application/x-ms-shortcut': FileTypeEnum.ARCHIVE,
  'application/vnd.android.package-archive': FileTypeEnum.ARCHIVE,
  'application/x-deb': FileTypeEnum.ARCHIVE,
  'application/x-rpm': FileTypeEnum.ARCHIVE,
  'application/x-dpkg': FileTypeEnum.ARCHIVE,
  'application/x-gtar': FileTypeEnum.ARCHIVE,
  'application/x-gtar-compressed': FileTypeEnum.ARCHIVE,
  'application/vnd.apple.installer+xml': FileTypeEnum.ARCHIVE,
  'application/x-dmg': FileTypeEnum.ARCHIVE,
  'application/x-bzip': FileTypeEnum.ARCHIVE,
  'application/msword': FileTypeEnum.OFFICE,
  'application/vnd.ms-powerpoint': FileTypeEnum.OFFICE,
  'application/vnd.ms-excel': FileTypeEnum.OFFICE,
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
    FileTypeEnum.OFFICE,
  'application/vnd.openxmlformats-officedocument.presentationml.presentation':
    FileTypeEnum.OFFICE,
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
    FileTypeEnum.OFFICE,
};

// File extension to file type mappings
export const EXTENSION_MAP: Record<string, FileType> = {
  pdf: FileTypeEnum.PDF,
  ai: FileTypeEnum.IMAGE,
  ps: FileTypeEnum.IMAGE,
  jpg: FileTypeEnum.IMAGE,
  jpeg: FileTypeEnum.IMAGE,
  png: FileTypeEnum.IMAGE,
  gif: FileTypeEnum.IMAGE,
  webp: FileTypeEnum.IMAGE,
  avif: FileTypeEnum.IMAGE,
  bmp: FileTypeEnum.IMAGE,
  tif: FileTypeEnum.IMAGE,
  tiff: FileTypeEnum.IMAGE,
  svg: FileTypeEnum.IMAGE,
  heic: FileTypeEnum.IMAGE,
  heif: FileTypeEnum.IMAGE,
  ico: FileTypeEnum.IMAGE,
  psd: FileTypeEnum.IMAGE,
  aac: FileTypeEnum.AUDIO,
  flac: FileTypeEnum.AUDIO,
  mp3: FileTypeEnum.AUDIO,
  wav: FileTypeEnum.AUDIO,
  wave: FileTypeEnum.AUDIO,
  oga: FileTypeEnum.AUDIO,
  ogg: FileTypeEnum.AUDIO,
  opus: FileTypeEnum.AUDIO,
  m4a: FileTypeEnum.AUDIO,
  m4b: FileTypeEnum.AUDIO,
  weba: FileTypeEnum.AUDIO,
  amr: FileTypeEnum.AUDIO,
  aiff: FileTypeEnum.AUDIO,
  aif: FileTypeEnum.AUDIO,
  au: FileTypeEnum.AUDIO,
  caf: FileTypeEnum.AUDIO,
  midi: FileTypeEnum.AUDIO,
  mid: FileTypeEnum.AUDIO,
  mpga: FileTypeEnum.AUDIO,
  mp2: FileTypeEnum.AUDIO,
  mp4: FileTypeEnum.VIDEO,
  m4v: FileTypeEnum.VIDEO,
  mkv: FileTypeEnum.VIDEO,
  webm: FileTypeEnum.VIDEO,
  avi: FileTypeEnum.VIDEO,
  mpg: FileTypeEnum.VIDEO,
  mpeg: FileTypeEnum.VIDEO,
  mov: FileTypeEnum.VIDEO,
  qt: FileTypeEnum.VIDEO,
  wmv: FileTypeEnum.VIDEO,
  mxf: FileTypeEnum.VIDEO,
  ts: FileTypeEnum.VIDEO,
  m2ts: FileTypeEnum.VIDEO,
  mts: FileTypeEnum.VIDEO,
  '3gp': FileTypeEnum.VIDEO,
  '3g2': FileTypeEnum.VIDEO,
  ogv: FileTypeEnum.VIDEO,
  ogm: FileTypeEnum.VIDEO,
  ogx: FileTypeEnum.VIDEO,
  flv: FileTypeEnum.VIDEO,
  f4v: FileTypeEnum.VIDEO,
  mpd: FileTypeEnum.VIDEO,
  zip: FileTypeEnum.ARCHIVE,
  rar: FileTypeEnum.ARCHIVE,
  '7z': FileTypeEnum.ARCHIVE,
  gz: FileTypeEnum.ARCHIVE,
  bz2: FileTypeEnum.ARCHIVE,
  bz: FileTypeEnum.ARCHIVE,
  xz: FileTypeEnum.ARCHIVE,
  zst: FileTypeEnum.ARCHIVE,
  sz: FileTypeEnum.ARCHIVE,
  lz: FileTypeEnum.ARCHIVE,
  lzma: FileTypeEnum.ARCHIVE,
  lz4: FileTypeEnum.ARCHIVE,
  tar: FileTypeEnum.ARCHIVE,
  'tar.gz': FileTypeEnum.ARCHIVE,
  'tar.bz2': FileTypeEnum.ARCHIVE,
  'tar.xz': FileTypeEnum.ARCHIVE,
  'tar.zst': FileTypeEnum.ARCHIVE,
  'tar.lz': FileTypeEnum.ARCHIVE,
  'tar.lz4': FileTypeEnum.ARCHIVE,
  'tar.sz': FileTypeEnum.ARCHIVE,
  'tar.br': FileTypeEnum.ARCHIVE,
  tgz: FileTypeEnum.ARCHIVE,
  tbz: FileTypeEnum.ARCHIVE,
  tbz2: FileTypeEnum.ARCHIVE,
  txz: FileTypeEnum.ARCHIVE,
  tlz: FileTypeEnum.ARCHIVE,
  tlz4: FileTypeEnum.ARCHIVE,
  iso: FileTypeEnum.ARCHIVE,
  dmg: FileTypeEnum.ARCHIVE,
  img: FileTypeEnum.ARCHIVE,
  pkg: FileTypeEnum.ARCHIVE,
  msi: FileTypeEnum.ARCHIVE,
  msix: FileTypeEnum.ARCHIVE,
  exe: FileTypeEnum.ARCHIVE,
  apk: FileTypeEnum.ARCHIVE,
  cab: FileTypeEnum.ARCHIVE,
  deb: FileTypeEnum.ARCHIVE,
  rpm: FileTypeEnum.ARCHIVE,
  sfx: FileTypeEnum.ARCHIVE,
  csv: FileTypeEnum.DATA,
  json: FileTypeEnum.DATA,
  txt: FileTypeEnum.DATA,
  log: FileTypeEnum.DATA,
  md: FileTypeEnum.DATA,
  yaml: FileTypeEnum.DATA,
  yml: FileTypeEnum.DATA,
  xlsx: FileTypeEnum.OFFICE,
  xls: FileTypeEnum.OFFICE,
  doc: FileTypeEnum.OFFICE,
  docx: FileTypeEnum.OFFICE,
  ppt: FileTypeEnum.OFFICE,
  pptx: FileTypeEnum.OFFICE,
  odp: FileTypeEnum.OFFICE,
  ods: FileTypeEnum.OFFICE,
  odt: FileTypeEnum.OFFICE,
};

// MIME prefix mappings for broader categorization
export const MIME_PREFIX_MAP = [
  { prefix: 'image/', type: FileTypeEnum.IMAGE },
  { prefix: 'audio/', type: FileTypeEnum.AUDIO },
  { prefix: 'video/', type: FileTypeEnum.VIDEO },
] as const satisfies ReadonlyArray<{ prefix: string; type: FileType }>;

// Filename delimiter candidates for parsing original filenames
export const ORIGINAL_DELIMITER_CANDIDATES = ['_', '-', ' ', '.'] as const;

// Type-safe delimiter type
export type OriginalDelimiterCandidate =
  (typeof ORIGINAL_DELIMITER_CANDIDATES)[number];

// Characters forbidden in filenames
export const FORBIDDEN_FILENAME_CHARS = /[\\/:*?"<>|]/g;

// Text file extensions eligible for AI text analysis
export const TEXT_EXTENSIONS = new Set([
  'txt',
  'text',
  'md',
  'markdown',
  'log',
  'json',
  'json5',
  'jsonl',
  'yaml',
  'yml',
  'csv',
  'tsv',
  'xml',
  'html',
  'htm',
  'css',
  'scss',
  'less',
  'js',
  'jsx',
  'ts',
  'tsx',
  'mjs',
  'cjs',
  'py',
  'rb',
  'go',
  'java',
  'kt',
  'swift',
  'rs',
  'php',
  'c',
  'cc',
  'cpp',
  'h',
  'hpp',
  'sh',
  'bash',
  'zsh',
  'ps1',
  'ini',
  'conf',
  'cfg',
  'toml',
  'properties',
  'r',
  'scala',
  'lua',
  'sql',
]);
