/**
 * Prompt building logic for image rename decisions.
 * Constructs prompts that evaluate if an image filename needs improvement.
 *
 * SECURITY: Filename is sanitized, description is AI-generated (no sanitization needed).
 * Page context is already sanitized by the formatter.
 */

import { formatPageContextInline } from '@/entrypoints/shared/context/page-context-formatter';
import { sanitizeForPrompt } from '@/entrypoints/shared/utils/prompt-sanitization';
import type { RenameDecisionParams } from './image-rename-decision-types';

/**
 * System prompt for image rename decision analysis.
 * Sets the conservative decision-making approach for the AI.
 */
export const RENAME_DECISION_SYSTEM_PROMPT = `You are a filename quality analyzer for images.
Decide if an image filename needs improvement based on its description, current name, and page context.

PRIMARY RULE: When page context (title/heading) is provided, the filename MUST contain recognizable keywords from that context. A timestamp + random code is insufficient.

Be CONSERVATIVE in your decisions:
- Generic names should be flagged for rename
- Meaningless hashes or UUID-style codes must be renamed
- Timestamp-only names almost always need improvement
- Poor formatting (ALL_CAPS_NO_SEPARATORS) is unacceptable
- Already descriptive, professional names should be kept
- When uncertain, prefer keeping the current filename

Reasons to RENAME (shouldRename: true):
1. **Missing page context keywords**: Page title/heading exists but filename lacks those terms
2. Generic names: "image", "photo", "download", "pic", "screenshot", "image (1)"
3. Meaningless hashes or UUIDs: "IMG_1234", "DSC_5678", "DCIM123", random hex strings
4. Timestamp-only names: "2024-01-15", "20240115_1430", dates without descriptive context
5. Poor formatting: ALL_CAPS_NO_SEPARATORS, unreadable structure
6. Mismatched content: filename doesn't reflect what's actually in the image

Reasons to KEEP (shouldRename: false) - ONLY when:
1. Filename already contains page title/heading keywords (if page context was provided)
2. Already descriptive and professional
3. Accurately reflects image content
4. Good balance of clarity and specificity

EVALUATION HIERARCHY:
- First: Check if page context keywords are present in filename → if missing, MUST rename
- Second: Evaluate if filename is descriptive of actual content
- Third: Check formatting quality

Real-world examples:
- "2025-11-18_14-22 s-l1600.webp" with page "Silent Angel Switch" → shouldRename: true (missing product name)
- "2025-11-18 Silent-Angel-Network-Switch.webp" with page "Silent Angel Switch" → shouldRename: false (has keywords)
- "IMG_1234.jpg" → shouldRename: true (meaningless code)
- "sunset-over-ocean.jpg" → shouldRename: false (descriptive)

Respond with JSON only: {"shouldRename": boolean, "confidence": 0.0-1.0, "reason": "...", "explanation": "..."}`;

/**
 * Build decision prompt for image rename analysis.
 * Evaluates filename quality based on description and page context.
 *
 * @param params - Decision parameters including filename and description
 * @returns Formatted decision prompt
 */
export function buildDecisionPrompt(params: RenameDecisionParams): string {
  // Sanitize filename (untrusted), but NOT description (AI-generated by our model)
  const sanitizedFilename = sanitizeForPrompt(params.currentFilename);

  const filenameLiteral = JSON.stringify(sanitizedFilename);
  // Description is already AI-generated, so JSON.stringify is sufficient
  const descriptionLiteral = JSON.stringify(params.description.trim());

  const contextLines = [
    `- Current filename: ${filenameLiteral}`,
    `- Image description: ${descriptionLiteral}`,
    `- File type: "${params.fileType}"`,
  ];

  // Add page context if available (already sanitized by formatter)
  const pageContextFormatted = formatPageContextInline(params.pageContext);
  if (pageContextFormatted) {
    contextLines.push(`- Source page: ${pageContextFormatted}`);
  }

  const decisionRules = [
    '1. Rename when the name is generic (e.g., "image", "photo", "download"), a meaningless hash/UUID, only a timestamp, severely formatted (ALL_CAPS_NO_SEPARATORS), or mismatched with the description.',
    '2. Keep the current name when it is already descriptive, professional, and properly formatted. When in doubt, keep it.',
  ];

  const pageSpecificParts: string[] = [];
  if (params.pageContext?.title) {
    pageSpecificParts.push(`title ${JSON.stringify(params.pageContext.title)}`);
  }
  if (params.pageContext?.heading) {
    pageSpecificParts.push(
      `heading ${JSON.stringify(params.pageContext.heading)}`,
    );
  }

  if (pageSpecificParts.length > 0) {
    decisionRules.push(
      `3. The source page mentions ${pageSpecificParts.join(
        ' and ',
      )}. If those specific names are missing from the filename, treat it as incomplete and choose shouldRename: true.`,
    );
  }

  return `You are evaluating whether an image filename needs improvement based on the content description and page context.

Context:
${contextLines.join('\n')}

Decision rules (IN ORDER OF PRIORITY):
${decisionRules.join('\n')}

CRITICAL: Rule #3 overrides all other considerations. A timestamp + generic code (like "2025-11-18_14-22 s-l1600") is NOT sufficient when meaningful page context exists. The filename MUST contain recognizable keywords from the source page title or heading.

Return JSON that matches this schema:
\`\`\`json
{
  "shouldRename": boolean,
  "confidence": number (between 0 and 1),
  "reason": "generic-name" | "meaningless-hash" | "timestamp-only" | "poor-formatting" | "already-descriptive" | "already-good" | "unknown",
  "explanation": string (optional, <= 150 characters)
}
\`\`\`

Examples:
1. Good filename (has page keywords):
{"shouldRename": false, "confidence": 0.82, "reason": "already-descriptive", "explanation": "Filename contains 'sunset beach' matching the page title."}

2. Needs rename (missing page context):
{"shouldRename": true, "confidence": 0.9, "reason": "generic-name", "explanation": "Filename is timestamp+code but missing 'Silent Angel Switch' from page title."}

3. Needs rename (timestamp only):
{"shouldRename": true, "confidence": 0.85, "reason": "timestamp-only", "explanation": "Filename lacks any keywords from page title 'Network Switch Product'."}

Respond with JSON only—no markdown, no explanations outside the JSON object.`;
}
